# 指定语言环境
language: python
python: 
  - "3.6"

branches:
  only:
    - master
    - source

install:
  - pip install -r requirements.txt

script:
  - python blog.py

after_surcess:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - mv ../tags/ ./tags/
  - mv ../blog/ ./blog/
  - mv ../img/ ./img/
  - mv ../*.html ./
  - cd ./public
  - git init
  - git config user.name "laomafeima"
  - git config user.email "laomafeima@gmail.com"
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master
# End: Build LifeCycle

env:
 global:
   - GH_REF: github.com/laomafeima/laomafeima.github.io.git
